server:
  port: 8080
  servlet:
    context-path: /api/v1
  error:
    include-message: always
    include-binding-errors: always
springdoc:
  api-docs:
    enabled: true
    groups:
      enabled: true
    path: /compie/api-docs
  cache:
    disabled: true
  swagger-ui:
    display-request-duration: true
    enabled: true
    path: /compie/swagger-ui
spring:
  application:
    name: compie
  redis:
    database: ${REDIS_DATABASE:1}
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:1234}
    timeout: 6000
balldontlie:
  host: ${BALLDONTLIE_URL:https://api.balldontlie.io}
  api-key: ${BALLDONTLIE_API_KEY:a2d2741d-fc47-45aa-8580-98edbfa6f9b2}